version: "3"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1001 #uid have to match permission of the piwigo folder
      - PGID=1001 #gid have to match permission of the piwigo folder
      - MYSQL_ROOT_PASSWORD=Derkom1soldat
      - TZ=Europe/Copenhagen #change timezone if needed
      - MYSQL_DATABASE=piwigo #optional
      - MYSQL_USER=piwigo_user #optional
      - MYSQL_PASSWORD=Derkom1soldat #optional
    volumes:
      - /<path to>/piwigo/piwigo_config/db:/config
    ports:
      - 3306:3306 #change port if needed
    restart: unless-stopped

  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1001 #uid have to match permission of the piwigo folder
      - PGID=1001 #gid have to match permission of the piwigo folder
      - TZ=Europe/Copenhagen #change timezone if needed
    volumes:
      - /<path to>/piwigo/piwigo_config/data:/config
      - /<path to>/piwigo/gallery:/gallery
    ports:
      - 8082:80 #change port if neede
    depends_on:
      - mariadb
    restart: unless-stopped
